name: chat_adapter
description: BLoC adapter between chat_core and UI layers.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.2.0
  equatable: ^2.0.7
  chat_core:
    path: ../chat_core

dev_dependencies:
  bloc_test: ^10.0.0
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
